/*
작성자 : 이혜리
기능 : 마스터 조교가 학기마다 토큰값을 생성하는 기능
 */
package cms.UserPackage;

import cms.ConnectDB.ConnectDB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author 이혜리
 */
public class CreateTokenPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateToken
     */
    public CreateTokenPage() {
        initComponents();
    }

    int semester = 0;
    int year = 0;
    int month = 0;
    String token = null;

    public void Create() { // 토큰 생성
        Calendar c = Calendar.getInstance();

        semester = 0;
        year = c.get(Calendar.YEAR);
        month = c.get(Calendar.MONTH);

        if (month >= 1 && month <= 6) {
            semester = 1;
        } else {
            semester = 2;
        }

        int random = (int) (Math.random() * (99999 - 10000 + 1)) + 10000;
        token = year + "@" + Integer.toString(random) + "?" + semester;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createToken_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createToken_button.setText("토큰 생성");
        createToken_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createToken_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel5.setText("토큰 생성");

        exit.setText("이전");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(createToken_button))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(80, 80, 80)
                .addComponent(createToken_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createToken_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createToken_buttonActionPerformed
        // TODO add your handling code here:
        ConnectDB db = new ConnectDB();
        Connection conn = null;
        PreparedStatement ps = null;

        CreateTokenPage c = new CreateTokenPage();
        c.Create();

        LocalDateTime localDateTime = LocalDateTime.now();
        DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("MM/dd");
        String currentDate = localDateTime.format(formatTime);

        try {
            conn = db.getConnection();

            if (currentDate.equals("3/1") || currentDate.equals("9/1")) {
                ps = conn.prepareStatement("insert into Token values(?,?,?)");

                ps.setString(1, c.token);
                ps.setInt(2, c.year);
                ps.setInt(3, c.semester);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, c.token + " 토큰 생성이 완료되었습니다.");
            } else {
                JOptionPane.showMessageDialog(null, "토큰 생성 기간이 아닙니다.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_createToken_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTokenPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTokenPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTokenPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTokenPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTokenPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createToken_button;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
